### PR TITLE
Use PlatformViewLink widget for Android WebView

### PR DESCRIPTION
**Pull request by plateaukao**
## Connection with issue(s)

Resolve issue: https://github.com/flutter/flutter/issues/41089

**[webview_flutter] Keyboard language can't change on Android** (https://github.com/flutter/flutter/issues/41089) is listed in issue (https://github.com/flutter/flutter/issues/61133) and it's fixed by flutter PR: https://github.com/flutter/plugins/pull/2883

Although this issue is reported to webview_flutter, it happens in **flutter_inappwebview** too, and especially for users who use google gboard as input method, and try to switch to Chinese input methods.

So, I ported the fix from **webview_flutter** plugin.

## Testing and Review Notes

Steps:
* You have to change flutter channel to **dev** in order to build this PR, since the so-called hybrid composition is now only available for flutter v1.20 or v1.21.
* Install Google gboard input method, and install chinese pinyin or chuyin input method, and launch InAppWebView with some website that needs some input.
* focus on the text field and see if it's possible to switch to pinyin input method in gboard.

## Screenshots or Videos
**Video with language switching issue**
Before applying the fix, all Chinese input methods will be displayed with just QWERTY input keyboard, which does not allow users to input any Chinese characters.

inappwebview_input_issue

**Video after applying the fix**
After applying the fix, the input method can be successfully switched, and be used to input Chinese.
inappwebview_input_issue_fixed

## To Do

- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by pichillilorenzo** [comment]
Thanks! I was waiting for the hybrid composition to be available on the stable channel before doing this. With hybrid composition, probably I can remove also some other workarounds.

I think we need to wait when the hybrid composition is available on the stable channel in order to merge this PR, what do you think?

**Comment by plateaukao** [comment]
that sounds good to me. :) I will keep tracking when it's merged to stable channel.

**Comment by LailaiMaster** [comment]
Try correcting the name to the name of an existing method, or defining a method named 'AndroidViewSurface'.
          return AndroidViewSurface( 
@plateaukao

**Comment by plateaukao** [comment]
Hello @pichillilorenzo ~  1.20 and 1.20.1 is released on [flutter stable channel.](https://flutter.dev/docs/development/tools/sdk/releases) If you have time to merge this PR, or integrate hybrid composition in any way in next version, it would be of great help! Thank you. :)

**Comment by tneotia** [comment]
@pichillilorenzo I think we are good to merge this if it looks good to you, since now we have an option to use this rather than forcing users to adopt Hybrid Composition. Also, no need for each user to include the `embedded_views_preview` in their `AndroidManifest` anymore, it is taken care of through the plugin itself.

**Comment by pichillilorenzo** [comment]
Thanks!

**Comment by tneotia** [comment]
Actually I discovered a bug with this yesterday I was trying to fix, but couldn't get to it. If you don't have the `android` tag (it just has to be there, no options actually have to be defined), the app doesn't run and says the parameter `android` is not defined. I think it has something to do with the way I grabbed the `useHybridComposition` bool - I queried it using `widget.initialOptions.android.useHybridComposition`.

This will have to be fixed before pushing a new release, do you have any idea what could be going wrong?

**Comment by pichillilorenzo** [comment]
Ok, I fixed also that! Thanks 👍

**Comment by plateaukao** [comment]
just FYI:
Flutter 1.22.0-12.1.pre is released in Beta channel on 9/17/2020. This release fixed the PlatformViewLink (Hybrid Composition) unstable issue described in https://github.com/flutter/flutter/issues/63897

**Pull request merged**
