### PR TITLE
Add proxy support for iOS

### PR DESCRIPTION
**Pull request by yerkejs**
## Connection with issue(s)

Connected to https://github.com/pichillilorenzo/flutter_inappwebview/issues/2244

## Testing and Review Notes

1. Connecting proxy (HTTP or SOCKS) like Charles, Proxyman and etc

## To Do

- [X] double check the original issue to confirm it is fully satisfied
- [X] add testing notes and screenshots in PR description to help guide reviewers

### CODE REVIEW

**Comment by pichillilorenzo** [comment]
This is cool, thanks! However, the API should not contain any "android" or "ios" prefix as this is something that was removed when coming from plugin version 5.
This is because you never know what setting or method you can implement and for what platform.
In general, I simply add it to the docs of the field/method/class if it is supported or not by a specific platform.

In this case, probably we could update the implementation of `types/proxy_rule.dart` with the iOS/macOS specific-fields, such as "bool allowFailover;" and in the code docs you would have something like this:
```dart
  /// A Boolean that indicates whether or not a proxy configuration allows failover to non-proxied connections.
  /// Failover isn’t allowed by default.
  ///
  ///**Officially Supported Platforms/Implementations**:
  ///- iOS
  bool allowFailover;
```

Because [WebKit.WKWebsiteDataStore.proxyConfigurations](https://developer.apple.com/documentation/webkit/wkwebsitedatastore/4264546-proxyconfigurations) accepts an array of [ProxyConfiguration](https://developer.apple.com/documentation/network/proxyconfiguration), this way we can set an array of different configuration.

What do you think?

**Comment by yerkejs** [comment]
Thanks for feedback, yeah makes sense, I'll update PR

**Comment by pichillilorenzo** [comment]
I was working on this feature to update it but it seems I'm not able to make it work.
My simple proxy server is not reached and the WKWebView navigation just fails with this log:
```
[pageProxyID=7, webPageID=8, PID=8226] WebPageProxy::didFailProvisionalLoadForFrame: frameID=1, isMainFrame=1, domain=NSURLErrorDomain, code=-999, isMainFrame=1, willInternallyHandleFailure=0
```
I'm on XCode 16.1 and a real iPhone with iOS 18.1.

How did you test it on iOS?

**Comment by pichillilorenzo** [comment]
It seems I'm now able to make it work. I will update this pull request soon with the new changes.

**Comment by pichillilorenzo** [comment]
I don't know why, but it seems Github didn't correctly recognize the commits using the command-line instructions.
Probably I didn't do something correctly when merging my commits.
However, the next plugin version `6.2.0-beta.3` will have this feature also on macOS, thanks for the support!

**Comment by pichillilorenzo** [comment]
@all-contributors please add @yerkejs for code

**Pull request closed without merging**
