### PR TITLE
Fix hybrid composition laggy

### PR DESCRIPTION
**Pull request by Doflatango**
Fix https://github.com/pichillilorenzo/flutter_inappwebview/issues/1386.

After change `initSurfaceAndroidView` to `initExpensiveAndroidView`, seems can fixes that proplem.
I need to check more code in case there has another thing needed to be changed, so i mark this PR as `Draft` currently.

### CODE REVIEW

**Comment by pichillilorenzo** [comment]
Ok, thanks! Did you test it with both Flutter 2 and 3 versions?

**Comment by pichillilorenzo** [comment]
From this line [webview_surface_android.dart#L99](https://github.com/flutter/plugins/blob/f55c7ffc6984c75e6b2b6a72a02b48064e0b5bc1/packages/webview_flutter/webview_flutter_android/lib/webview_surface_android.dart#L99) of the webview_flutter plugin, `initExpensiveAndroidView` is used for Hybrid composition, otherwise `initSurfaceAndroidView`.
So I think it should work

**Comment by Doflatango** [comment]
There is a compatibility problem, `initExpensiveAndroidView` requires Flutter >= 3.0.0. So we need to update the required minimum Flutter version to 3.0.0😅 @pichillilorenzo

**Comment by Doflatango** [comment]
Hi @pichillilorenzo , from [this page](https://github.com/pichillilorenzo/flutter_inappwebview/tags ), this PR is not actually publish in v5.6.0.

**Comment by Doflatango** [comment]
> Hi @pichillilorenzo , from [this page](https://github.com/pichillilorenzo/flutter_inappwebview/tags), this PR is not actually publish in v5.6.0.

Sorry, my mistask, I forget to update pubspec.yaml.

**Comment by Manuito83** [comment]
Out of curiosity: is this PR necessary if using Flutter 3.0.0 (as per Lorenzo's comment that this is already in the standard webview package)?

**Comment by pichillilorenzo** [comment]
@Doflatango are you sure? I tried using latest flutter version 2 available (2.13.0-0.4.pre) and it was working!

**Comment by pichillilorenzo** [comment]
@Manuito83 yes, this PR is necessary! This plugin and the webview_flutter plugin are different webview implementation! I’m not using it

**Comment by pichillilorenzo** [comment]
@Doflatango Ok, yes `PlatformViewsService.initExpensiveAndroidView` is not defined in lower version.
If possible, I will try to make a workaround to still use it

**Comment by pichillilorenzo** [comment]
released `5.6.0+1` with the fix for Flutter 2

**Comment by pichillilorenzo** [comment]
Ok, no it's not working as expected

**Comment by pichillilorenzo** [comment]
@Doflatango I tried some workarounds but I think that the best solution is to bump the minimum Flutter version to 3 as you already said, or to Flutter version 2.11, that should implement `PlatformViewsService.initExpensiveAndroidView` static method

**Comment by Doflatango** [comment]
@pichillilorenzo I have no idea that how to compatible with both Flutter 2 and 3 in this problem, and I would recommend bump to Flutter 3 due to all version between 2.10.5 and 3.0.0 are beta version, it make no sense.

**Comment by pichillilorenzo** [comment]
@Doflatango Ok, so I will create a new version `5.6.0+2` that will revert this pull request, and then a new version `5.7.0` that will implement it with the minimum Flutter version to 3.0.0

**Comment by Doflatango** [comment]
@pichillilorenzo Thanks!

**Pull request merged**
