### PR TITLE
Issue 1909 privacy manifest

### PR DESCRIPTION
**Pull request by mvolpato**
## Connection with issue(s)

Resolve issue #1909

## Testing and Review Notes

I used the same approach that has been used for [Flutter packages](https://github.com/flutter/packages/pull/5846/). I could not test because of some dependency issues with the platform interface package (`PlatformWebViewEnvironmentCreationParams` cannot be found).

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by SputNikPlop** [comment]
Tested and it should be fine, appears in Xcode privacy nutrition list just fine.

**Review by LongXiangGuo — APPROVED** [review]

**Comment by romaCaldeira** [comment]
Hey guys, when will we have the next version with these adjustments?

**Comment by danbeechbloom** [comment]
+1 for this, any ETA on release?

**Comment by kinako0626-ota** [comment]
When will a version be released that reflects this PR?

**Comment by realDiegoR** [comment]
Only mentioning that it's April 10th. :/ ...

**Comment by S-ecki** [comment]
Hey @mvolpato, how did you proceed with the error mentioned in your PR description?
(`I could not test because of some dependency issues with the platform interface package (PlatformWebViewEnvironmentCreationParams cannot be found).`
We are having the same problems, both when using some fork that fixes the privacy manifest problem, as well as when we try to fix it ourselves.

**Comment by mvolpato** [comment]
> Hey @mvolpato, how did you proceed with the error mentioned in your PR description? (`I could not test because of some dependency issues with the platform interface package (PlatformWebViewEnvironmentCreationParams cannot be found).` We are having the same problems, both when using some fork that fixes the privacy manifest problem, as well as when we try to fix it ourselves.

Sorry, I do not remember. Try to upgrade your dependencies

**Pull request closed without merging**
