### PR TITLE
Migrate to package:web for Wasm compatibility

### PR DESCRIPTION
**Pull request by johnpryan**
This migrates from `dart:html` to `package:web` for Wasm compatibility

### CODE REVIEW

**Comment by pichillilorenzo** [comment]
[web package](https://pub.dev/packages/web) seems to be highly experimental currently.
Also, using that package would increase the minimum Dart SDK to `^3.2.0`.
Probably, the best way to support it would be to create a new implementation package for web wasm instead of updating the current one.

**Comment by The-RootCause** [comment]
WASM is getting stable soon. Many packages are now compatible with Wasm. 
@pichillilorenzo  any plans to make it compatible with WASM ?
Thank you

**Comment by The-RootCause** [comment]
@johnpryan 
Your version is still not fully wasm compatible, 
```
../../.pub-cache/hosted/pub.dev/flutter_inappwebview_web-1.0.8/lib/web/in_app_web_view_web_element.dart:7:1: Error: JS interop library 'dart:js' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'dart:js' as js;
^
../../.pub-cache/hosted/pub.dev/flutter_inappwebview_web-1.0.8/lib/web/platform_util.dart:5:1: Error: JS interop library 'dart:js' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'dart:js' as js;
^
```

Anyway you can migrate the js to js_interop ?
Thank you

**Comment by p-mazhnik** [comment]
@The-RootCause I created a PR with migration to js_interop: https://github.com/pichillilorenzo/flutter_inappwebview/pull/2067

**Comment by johnpryan** [comment]
It looks like #2067 addresses this issue, closing.

**Pull request closed without merging**
