### PR TITLE
feature/flutter-3.22.X

### PR DESCRIPTION
**Pull request by EArminjon**
## Connection with issue(s)

This PR resolve and should close following PR :

- https://github.com/pichillilorenzo/flutter_inappwebview/pull/2209
- https://github.com/pichillilorenzo/flutter_inappwebview/pull/2190
- https://github.com/pichillilorenzo/flutter_inappwebview/pull/2189
- https://github.com/pichillilorenzo/flutter_inappwebview/pull/2182
- https://github.com/pichillilorenzo/flutter_inappwebview/pull/2156
- https://github.com/pichillilorenzo/flutter_inappwebview/pull/2155

## Testing and Review Notes

Required to run on flutter 3.22.X

## To Do

- [X] double check the original issue to confirm it is fully satisfied
- [X] add testing notes and screenshots in PR description to help guide reviewers
- [X] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by redDwarf03** [comment]
Perhaps a flutter_inappwebview_plus lib could be created to keep the project alive?
Cc @AlexV525 @Doflatango @Manuito83 @EArminjon

**Comment by AlexV525** [comment]
One workaround IIRC is to use `webview_flutter_android: 3.16.1`.

Regarding keeping the project alive. @pichillilorenzo usually shows every half year. It could be good if he's open to more contributors or let some organizations he trusts involve the management. Maybe we should discuss this in a separate thread.

**Comment by Manuito83** [comment]
I sent him a private email but he hasn't answered yet, sadly

**Comment by redDwarf03** [comment]
> I sent him a private email but he hasn't answered yet, sadly

Me too few days ago

**Comment by EArminjon** [comment]
Hello @pichillilorenzo,

Can you check this PR please ?

**Comment by stan-at-work** [comment]
@pichillilorenzo You're really f*cking with us here. Please fix your sh*t, or deprecate the package if you're not interested anymore.

**Comment by pichillilorenzo** [comment]
Released new version 6.1.0 with the fix.

The proguard file has not been updated.
This update requires latest flutter 3.24 version and I didn't have any problem compiling the package example for Android with the current proguard file (without the `-dontwarn android.window.BackEvent`).

**Comment by AlexV525** [comment]
> Released new version 6.1.0 with the fix.
> 
> The proguard file has not been updated. This update requires latest flutter 3.24 version and I didn't have any problem compiling the package example for Android with the current proguard file (without the `-dontwarn android.window.BackEvent`).
> 
> Can you try? Thanks!

IIRC it actually wouldn't cause a compile issue, but a runtime issue that some classes are missing when opening the WebView.

**Comment by EArminjon** [comment]
> Released new version 6.1.0 with the fix.
> 
> The proguard file has not been updated.
> This update requires latest flutter 3.24 version and I didn't have any problem compiling the package example for Android with the current proguard file (without the `-dontwarn android.window.BackEvent`).
> 
> Can you try? Thanks!

Sorry for the delay. Amazing work, all works perfectly as expected ! Thanks a lot @pichillilorenzo

**Pull request closed without merging**
