### PR TITLE
[web] migrate to pkg:web and js_interop

### PR DESCRIPTION
**Pull request by p-mazhnik**
Resolves https://github.com/pichillilorenzo/flutter_inappwebview/issues/2052

Depends on https://github.com/pichillilorenzo/flutter_inappwebview/pull/2058

### CODE REVIEW

**Comment by GelistirmeKF** [comment]
@pichillilorenzo   @p-mazhnik  we urgently need this merge, could you please commit or create a fork?

**Comment by arrrrny** [comment]
@p-mazhnik @zh4ngx @GelistirmeKF Open your PR on the forked project [here](https://github.com/arrrrny/zikzak_inappwebview) and I will merge. There is a new package now. [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview)

**Comment by jezell** [comment]
@GelistirmeKF great that @arrrrny is maintaining a fork, but if you want to quick fix:

```yaml
dependency_overrides:
  flutter_inappwebview_web:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview
      path: flutter_inappwebview_web
      ref: 54dc69a918e898c18980af66f5a32f456ef3c232
```

**Comment by GelistirmeKF** [comment]
> @GelistirmeKF great that @arrrrny is maintaining a fork, but if you want to quick fix:
> 
> ```yaml
> dependency_overrides:
>   flutter_inappwebview_web:
>     git:
>       url: https://github.com/pichillilorenzo/flutter_inappwebview
>       path: flutter_inappwebview_web
>       ref: 54dc69a918e898c18980af66f5a32f456ef3c232
> ```

Hi all, thank you for progress. I will try the new version and inform you

**Comment by pichillilorenzo** [comment]
@all-contributors please add @p-mazhnik for code

**Pull request merged**
