### PR TITLE
[web] fix web callbacks

### LINKED ISSUE #2026: [Web] onLoadStart not invoked in Flutter 3.19.0
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.19.0        |
| Plugin version        |      6.0.0         |
| Google Chrome version |        121.0.6167.160       |

I've tried to figure out what is going on and I found in web_support.js(line 22)
`var iframe = document.getElementById(iframeId);`
the iframe is null but the iframe element can be found in Chrome dev mode.

### LINKED ISSUE #2045: [Flutter Web] evaluateJavascript is broke in latest version.
## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |   3.19.1   |
| Plugin version        |  6.0.0  |
| macOS version         |  Sonoma 14.2.1  |

Device information: MacBook Pro. 14-inch, 2023.

## Description

**Expected behavior:** 
[Flutter Web]
inAppWebViewController.evaluateJavascript(source: "functionName();"); works perfectly fine in flutter version 3.16.4. 

**Current behavior:** 
[Flutter Web]
inAppWebViewController.evaluateJavascript(source: "functionName();"); stopped working in flutter 3.19.1.

## Steps to reproduce

1. Upgrade to latest version of flutter.
2. add the html initial file to InAppWebView (which has a script file connected to the html with the following function name 'abc') .
3.  Store the web view controller in a variable.
   onWebViewCreated: (InAppWebViewController controller) {
                        inAppWebViewController = controller;
                      },
4. call inAppWebViewController.evaluateJavascript(source: "abc();"); somewhere in the app, mostly in onTap property of an inkwell.
5. the 'abc' function present in the script file is never triggered.

## Summarry

I'm currently using flutter web and the inAppWebViewController.evaluateJavascript was working perfectly fine in version 3.16.4. I recently upgraded to 3.19.1 and it stopped working. There was no code modification.

Please let me know me if you need anything else. Really appreciate the work you have done for this package.

### LINKED ISSUE #2046: [Flutter Web] [Flutter 3.19.x] Callbacks (onLoadStart, onLoadStop, onConsoleMessage, onUpdateVisitedHistory) not firing
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       | 3.19.1 |
| Plugin version        | 6.0.0 |
| Google Chrome version | 121.0.6167.184 (Official Build) (arm64)  |

Device information: Apple M2 (14.0 (23A344))

## Description

**Expected behavior:** 
All web supported callbacks to work like onLoadStart, onLoadStop, onConsoleMessage, onUpdateVisitedHistory 

**Current behavior:** 
Only onWebViewCreated seems to be working
## Steps to reproduce
load html as data in InAppWebView and execute console message in any window load function

### PR DESCRIPTION
**Pull request by p-mazhnik**
Fixes #2026, fixes #2045, fixes #2046

Related to https://github.com/flutter/flutter/issues/143922

### CODE REVIEW

**Comment by asarkar101** [comment]
@p-mazhnik you didn't assign any reviewer.

**Comment by p-mazhnik** [comment]
@asarkar101 I am not a maintainer of this repository, therefore it is not possible to request reviews.

**Comment by sanalkv** [comment]
@pichillilorenzo Please kindly review this.

**Comment by sanalkv** [comment]
@p-mazhnik looks like the owner is not active :( @pichillilorenzo

**Comment by GelistirmeKF** [comment]
@pichillilorenzo This issue is so important for us, please consider this commit.

**Comment by david98pp** [comment]
@p-mazhnik How can I test your branch or import your branch to my project with your solution?

**Comment by p-mazhnik** [comment]
@david98pp you can add dependency override
```yml
dependency_overrides:
  flutter_inappwebview_web:
    git:
      url: git@github.com:p-mazhnik/flutter_inappwebview.git
      path: flutter_inappwebview_web
      ref: 7cac4c3c0ce50302cb9144901f425d00e4bf4870 
      # or ref: web-fix
```

**Comment by david98pp** [comment]
@p-mazhnik the method onUpdateVisitedHistory is still not working for me, do I have to do anything extra? or any solution?

**Comment by david98pp** [comment]
@p-mazhnik the error is: DOMException: Failed to read a named property 'history' from 'Window': Blocked a frame with origin "http://localhost:58988" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:58988/assets/packages/flutter_inappwebview_web/assets/web/web_support.js

**Comment by asarkar101** [comment]
> @p-mazhnik the error is: DOMException: Failed to read a named property 'history' from 'Window': Blocked a frame with origin "http://localhost:58988" from accessing a cross-origin frame. at HTMLIFrameElement. (http://localhost:58988/assets/packages/flutter_inappwebview_web/assets/web/web_support.js

same issue

**Comment by andynvt** [comment]
does this make `onProgressChanged` working?

**Comment by andynvt** [comment]
@p-mazhnik can you also fix `onProgressChanged` and `evaluateJavascript` functions not working on Flutter Web? Thank you

**Comment by yashharkhani** [comment]
@andynvt, Did you found solution to `evaluateJavascript` issue ?

I’m currently facing an issue with the evaluateJavascript function on the web platform. My entire app depends on this functionality, and I am unable to deploy it to the web due to this problem.

Any help or updates would be greatly appreciated, as I’m stuck and unable to proceed with my deployment.

Thank you.

**Comment by andynvt** [comment]
> @andynvt, Did you found solution to `evaluateJavascript` issue ?
> 
> I’m currently facing an issue with the evaluateJavascript function on the web platform. My entire app depends on this functionality, and I am unable to deploy it to the web due to this problem.
> 
> Any help or updates would be greatly appreciated, as I’m stuck and unable to proceed with my deployment.
> 
> Thank you.

@yashharkhani Not yet unfortunately

**Comment by p-mazhnik** [comment]
@andynvt
> can you also fix onProgressChanged and evaluateJavascript functions not working on Flutter Web?

`onProgressChanged` wasn't supported for web in this package:
https://github.com/pichillilorenzo/flutter_inappwebview/blob/4c58653113573558ea5be880aca931e85b23da7e/flutter_inappwebview_platform_interface/lib/src/in_app_webview/platform_webview.dart#L122-L127

@yashharkhani  @andynvt 

`evaluateJavascript` is working for me in this branch. I use flutter 3.19 and 3.22. Here is the commit where I tested it: 
https://github.com/p-mazhnik/flutter_inappwebview/commit/295ff82d42b65cf7f93a2af142be699663787f3e

Do you have any steps to reproduce?

**Comment by andynvt** [comment]
@p-mazhnik It seems it's not working for me. I use this URL for testing. 
```
https://99rnp6er5kop15.embednotionpage.com/Notion-test-page-3d941e191ea94e648c50d85a160cd333
```

```dart
await controller.evaluateJavascript(source: 'document.getElementsByClassName("layout");');
    await controller.evaluateJavascript(
      source:
          'document.getElementsByClassName("layout")[0].setAttribute("style", "--margin-width: 10px; padding-bottom: 0px;");',
    );
```


Result (not working with `controller. evaluateJavascript`
ScreenShot 2024-07-11 at 12 28 36


Result when I call javascript in Devtool - Console
ScreenShot 2024-07-11 at 12 29 46

**Comment by p-mazhnik** [comment]
If you're trying to access third-party site from your `localhost` or just from the different origin, this is expected that most of the functions won't work. Browsers block scripts trying to access a frame with a different origin, for security reasons. 
Typical message in console would be `Blocked a frame with origin "http://localhost/" from accessing a cross-origin frame`

**Comment by andynvt** [comment]
Thanks for your response @p-mazhnik. Unfortunately, I deployed it to firebase hosting. And it remains the same issue. (evaluateJavascript not working)

**Comment by skalex4** [comment]
> @andynvt
> 
> > can you also fix onProgressChanged and evaluateJavascript functions not working on Flutter Web?
> 
> `onProgressChanged` wasn't supported for web in this package:
> 
> https://github.com/pichillilorenzo/flutter_inappwebview/blob/4c58653113573558ea5be880aca931e85b23da7e/flutter_inappwebview_platform_interface/lib/src/in_app_webview/platform_webview.dart#L122-L127
> 
> @yashharkhani @andynvt
> 
> `evaluateJavascript` is working for me in this branch. I use flutter 3.19 and 3.22. Here is the commit where I tested it: [p-mazhnik@295ff82](https://github.com/p-mazhnik/flutter_inappwebview/commit/295ff82d42b65cf7f93a2af142be699663787f3e)
> 
> Do you have any steps to reproduce?

Thanks a lot @p-mazhnik! 

It's working with the mentioned commit ref.  

@andynvt, For web even after disabling CORS there is a internal CORS thrown while accessing iframe of diff domain. 

Please make sure that the domain of the site in webview and flutter site are exactly same.

**Comment by andynvt** [comment]
> @andynvt, For web even after disabling CORS, there is a internal CORS thrown while accessing iframe of diff domain. basically, it browser restricts you to even access the iframe inside site of diff domain.
> 
> Please make sure that the domain of the site in webview and flutter site are exactly same

In my case, do you mean my firebase domain or `embednotionpage` domain?

**Comment by skalex4** [comment]
For me, 

when I hosted my flutter app @ xyz.com and in webview I loaded abc.com. 

- It didn't work. It was giving me CORS error while accessing the iFrame. 
- Because of that in web_support under `createFlutterInAppWebView` it was not able to find the contentWindow on iFrame. 
- Thus, in `evaluateJavascript`  `iframe.contentWindow`  was null. 



But when I host flutter app @ abc.com/0.0.1 and in webview I loaded abc.com, it worked. 
- Because of same domain - NO CORS.


Try out this approach, 

it not able to do this, look into how you can allow "cross origin policy: *" in both domains.

**Comment by andynvt** [comment]
I cannot host the embedded webview on my server, it's in another 3rd service. I think most webview cases will look like my case (showing a 3rd party website iframe). So the `evaluateJavascript` won't work in that case, right?

**Comment by skalex4** [comment]
Yes @andynvt, It would be tough in that case. Try to look for allowing CORS on your site.

**Comment by sanalkv** [comment]
Can you guys check if this sample code is giving output using this branch? , It's not working for me, unfortunately.

`InAppWebView(
  initialUrlRequest: URLRequest(url: WebUri('https://flutter.dev')),
  initialUserScripts: UnmodifiableListView<UserScript>([
    UserScript(
        source: "var foo = 49;",
        injectionTime: UserScriptInjectionTime.AT_DOCUMENT_START),
    UserScript(
        source: "var bar = 2;",
        injectionTime: UserScriptInjectionTime.AT_DOCUMENT_END),
  ]),
  onLoadStop: (controller, url) async {
    var result = await controller.evaluateJavascript(source: "foo + bar");
    print(result); // 51
  },
),`

**Comment by sanalkv** [comment]
> If you're trying to access third-party site from your `localhost` or just from the different origin, this is expected that most of the functions won't work. Browsers block scripts trying to access a frame with a different origin, for security reasons. Typical message in console would be `Blocked a frame with origin "http://your-site/" from accessing a cross-origin frame`

I'm going through the same right now. Is there any resolution for this ?

**Comment by andynvt** [comment]
@p-mazhnik Should you release a new package for this? it seems the author didn't work on this repo anymore

**Comment by madhavibrillio** [comment]
@p-mazhnik  can we please merge this PR and release a new version?
We are facing lot of issues because of this

**Comment by sanalkv** [comment]
Maybe instead of a new package, someone who is interested can take ownership of this package and maintain it. You can mail the developer directly. Owner - pichillilorenzo@gmail.com

**Comment by madhavibrillio** [comment]
@pichillilorenzo  can we please merge this PR and release a new version? We badly need this fix

**Comment by arrrrny** [comment]
@madhavibrillio @sanalkv @andynvt @hn-n @skalex4 @p-mazhnik @asarkar101 @david98pp @GelistirmeKF Open your PR on the forked project [here](https://github.com/arrrrny/zikzak_inappwebview) and I will merge. There is a new package now. [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview)

**Comment by fawdlstty** [comment]
@arrrrny The author is back #2268

**Comment by arrrrny** [comment]
> @arrrrny The author is back #2268

I am glad

**Pull request merged**
