### PR TITLE
Exposed "shared" property of HttpServer bind method to support more use-cases.

### PR DESCRIPTION
**Pull request by LugonjaAleksandar**

### CODE REVIEW

**Comment by LugonjaAleksandar** [comment]
@pichillilorenzo please have a look at the PR in a reasonable time-frame. It doesn't change anything, keeping default values as they were. But it exposes a critical functionality that we need as a company on our project. Thank you in advance!

**Review by Sinishisimus — APPROVED** [review]

**Review by filipljusic — APPROVED** [review]

**Comment by pichillilorenzo** [comment]
The "master" branch is only for plugin version >= 6.0.0, for version 5.x.x the current correct branch is https://github.com/pichillilorenzo/flutter_inappwebview/tree/v5.7.0

**Comment by LugonjaAleksandar** [comment]
We are currently using 5.4.4+3 version

**Comment by pichillilorenzo** [comment]
Yes, I will merge it here for master and then add it as well on 5.7.0 with 5.7.1

**Comment by pichillilorenzo** [comment]
@all-contributors please add @LugonjaAleksandar for code

**Comment by pichillilorenzo** [comment]
Released v5.7.1

**Comment by pichillilorenzo** [comment]
If you want, you can add your App to the Official Showcase page here: https://inappwebview.dev/showcase/ (Follow the [Submit App Guide](https://inappwebview.dev/submit-app/)) 👍

**Comment by LugonjaAleksandar** [comment]
Thank you for the fast reply and action on the PR!

**Pull request merged**
