### PR TITLE
fix(ios): Xcode 16 build issue

### PR DESCRIPTION
**Pull request by arrrrny**
## Connection with issue(s)

Resolve issues #2278 #2201 #2279 #2202 

## To Do

- [X] double check the original issue to confirm it is fully satisfied
- [X] add testing notes and screenshots in PR description to help guide reviewers
- [X] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by arrrrny** [comment]
In the meantime before merge, can be refererenced as
```
  flutter_inappwebview:
    git:
      url: https://github.com/arrrrny/flutter_inappwebview.git
      path: flutter_inappwebview
      ref: gitref
 ```

**Comment by 1057437122** [comment]
> flutter_inappwebview:
>     git:
>       url: https://github.com/arrrrny/flutter_inappwebview.git
>       path: flutter_inappwebview
>       ref: gitref

I changed the import like this, but face a new error: /Users/developer/.pub-cache/git/flutter_inappwebview-7534e8de6f672917e9ab4edf5c3a0959715c0aa7/flutter_inappwebview/lib/src/webview_environment/webview_environment.dart:
12:14: Error: Type 'PlatformWebViewEnvironmentCreationParams' not found.

**Comment by MrLightful** [comment]
> lib/src/webview_environment/webview_environment.dart:12:14: Error: Type 'PlatformWebViewEnvironmentCreationParams' not found.

Same.

**Comment by arrrrny** [comment]
You can use my new package zikzak_inappwebview fork of this package that I will keep maintaining. Thanks @pichillilorenzo for developing/maintaining this package for a long time. I guess he is busy or on vacataion. I am the builder of Flutter Vendure (open source headless commerce framework) package. [Vendure](https://vendure.io)  Please open your PRs there and I am happy to check them and merge them by Monday.

**Comment by MrLightful** [comment]
> I guess he is busy or on vacataion.

In [this issue](https://github.com/pichillilorenzo/flutter_inappwebview/issues/2268#issuecomment-2340182822), he says he is planning to return back to the project (this month?). You can let ppl in the thread now about your fork, coz some of them were looking for something like this.

**Comment by redDwarf03** [comment]
> You can use my new package [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview) fork of this package that I will keep maintaining. Thanks @pichillilorenzo for developing/maintaining this package for a long time. I guess he is busy or on vacataion. I am the builder of Flutter Vendure (open source headless commerce framework) package. [Vendure](https://vendure.io) Please open your PRs [here](https://github.com/arrrrny/zikzak_inappwebview) and I am happy to check them and merge them by Monday.

@EArminjon

**Comment by EArminjon** [comment]
(don't close this PR, phill seems to be bakc)

**Pull request closed without merging**
