### PR TITLE
Fixed Xcode 16 build failed `error: method does not override any method from its superclass`

### PR DESCRIPTION
**Pull request by andychucs**
20th September 2024 Update:

**WARNING:** this change will cause Xcode 15 build errors if you still want to compile by old versions, do not use it. I am working on how to fix that now, if anyone knows a workaround, please let me know or just open a pr. 
**Because of that I made another version to fix it, please try to change ref to `xcode-15-fix` and report how it works.**
https://github.com/andychucs/flutter_inappwebview/pull/3

---------------

I made a few different changes based on other pr.I keep the override function evaluateJavaScript as public instead of delete or change as open.

Before the maintainer fixes it, add this in `pubspec.yaml`.
```
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios
```
If you need it in the macOS app, also update your dependencies to include:
```
dependency_overrides:
  flutter_inappwebview_macos:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_macos
```

## Connection with issue(s)

Resolve issue #2221 #2278 #2279  #2201 

Connected to #???

## Testing and Review Notes

**WARNING:** this change may cause Xcode 15 build errors if you still want to compile by old versions, do not use it. I am working on how to fix that now, if anyone knows a workaround, please let me know or just open a pr.

## To Do

- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by DarkMarksDoe** [comment]
Hey, nice to see your PR, just as a comment, there's another PR solving this issue:

https://github.com/pichillilorenzo/flutter_inappwebview/pull/2241/files

**Review by tozu — APPROVED** [review]

**Comment by andychucs** [comment]
I missed checking the same code to the macOS module.
Thanks for fixing this issue @dhirajhimani .

**Review by GabriellArthur — APPROVED** [review]

**Comment by SzymonDziak** [comment]
please ping me when this is resolved

**Comment by nabiarshad** [comment]
please ping me when this is resolved

**Review by ming-chu — APPROVED** [review]
LGTM, Thank you!

**Comment by czegarram** [comment]
please ping me when this is resolved

**Comment by ueman** [comment]
These changes will fail on Xcode version lower than 16 due to the same error this is trying to fix. I'm guessing you need to annotate the methods with `@available(...)` annotations

**Comment by andychucs** [comment]
@ueman Thanks for comment.

I'm not sure if it's correct to add annotations. I don't have a lower version of Xcode to test now.

I have checked the developer docs. It looks like there haven't been any updates to `evaluateJavaScript` and there's no new extension of `WKWebView` for iOS 18.0. Is it just that Xcode 16 doesn't allow overriding without the `@MainActor` annotation? Or should we not override this function at all?

Maybe we should add an extension to InAppWebView to fix.

**Comment by ueman** [comment]
After reading this https://stackoverflow.com/a/74364030, it seems you're right about not adding annotations. Instead, the code should be more explicit about the specific version of the method (at least I hope so, I haven't yet tested it)

**Review by EvGeniyLell — APPROVED** [review]

**Review by studiogaram — APPROVED** [review]

**Comment by kalpeshp0310** [comment]
I’m currently using Xcode 15, while my colleague is on Xcode 16. I can confirm that the changes in this PR resolved the build issues on Xcode 16. However, it still breaks the build on Xcode 15 with the same error.

**Comment by andychucs** [comment]
> I’m currently using Xcode 15, while my colleague is on Xcode 16. I can confirm that the changes in this PR resolved the build issues on Xcode 16. However, it breaks the build on Xcode 15 with the same error.

@kalpeshp0310 Thanks for comment.
Can you paste the error message if possible?

**Comment by ming-chu** [comment]
@andychucs I am not sure if the [Conditional-Compilation-Block](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/statements/#Conditional-Compilation-Block) can help.

**Comment by CPRmichel** [comment]
Can this PR be merged without pichillilorenzo ?

**Comment by kalpeshp0310** [comment]
> > I’m currently using Xcode 15, while my colleague is on Xcode 16. I can confirm that the changes in this PR resolved the build issues on Xcode 16. However, it breaks the build on Xcode 15 with the same error.
> 
> @kalpeshp0310 Thanks for comment. Can you paste the error message if possible?

```
Swift Compiler Error (Xcode): Method does not override any method from its superclass
/Users/kalpeshpatel/.pub-cache/git/flutter_inappwebview-615214fb2fd3f830955d526cfb6698d6e20b7b7a/flutter_inappwebview_ios/ios/Classes/InAppWebView/InAppWebView.swift:1431:25

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Could not build the application for the simulator.
```

**Comment by andychucs** [comment]
Can you paste the `WebKit.WKWebView` code about `evaluateJavaScript` on Xcode 15?
@kalpeshp0310 
截屏2024-09-19 23 22 52

**Comment by kalpeshp0310** [comment]
> Can you paste the `WebKit.WKWebView` code about `evaluateJavaScript` on Xcode 15? And I made a different version of this fix, changing this func to private and renaming it. Can you try it on Xcode 15? `ref: xcode-15-fix` @kalpeshp0310 截屏2024-09-19 23 22 52

I could find a few references in `WebKit.WKWebView`.

Screenshot 2024-09-19 at 11 41 37 PM
Screenshot 2024-09-19 at 11 42 16 PM


Also, the build is working fine on `xcode-15-fix` branch on Xcode-15. 👍

**Comment by ming-chu** [comment]
@kalpeshp0310 Thank you very much for the testing on Xcode 15! ❤️

**Comment by EArminjon** [comment]
Does this change is retro compatible with xode 15 ?

**Comment by pichillilorenzo** [comment]
Released new version 6.1.0 with the fix

**Comment by adamazlo** [comment]
Thank you!!!!!!

**Comment by fauzynurn** [comment]
> > Does this change is retro compatible with xcode 15 ?
> 
> No. Please read the above discussion and the update in the issue description to learn why

Just to clarify, so this is not backward compatibility with the xcode 15?

**Pull request closed without merging**
