### PR TITLE
Fixed error in InterceptAjaxRequestJS 'Failed to set responseType property'

### PR DESCRIPTION
**Pull request by EArminjon**
## Description : 

InAppWebView fail to intercept sync ajax query. 

From android chrome console : 

Capture d’écran 2023-12-06 à 14 50 19
(Js inspector)
Capture d’écran 2023-12-06 à 14 50 14

## To reproduce

initialOptions: 
   - useShouldInterceptAjaxRequest: true
   - javaScriptEnabled: true

initialData: 
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AJAX Example</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>

<button id="fetchDataBtn">Obtenir des données via AJAX</button>

<script>
    $('#fetchDataBtn').on('click', function () {
        $.ajax({
            url: 'https://jsonplaceholder.typicode.com/todos/1', // free open api
            async: false,
            method: 'GET',
            success: function (response) {
                console.log('Response AJAX :', response);
            },
            error: function (error) {
                console.error('Erreur AJAX :', error);
            }
        });
    });
</script>

</body>
</html>
```

```dart
Future<AjaxRequestAction> _onAjaxProgress(
      InAppWebViewController controller,
      AjaxRequest? ajaxRequest,
      ) async {
    print('test _onAjaxProgress $ajaxRequest');
    return AjaxRequestAction.PROCEED;
  }

  Future<AjaxRequestAction?> _onAjaxReadyStateChange(
    InAppWebViewController controller,
    AjaxRequest ajaxRequest,
  ) async {
    print('test _onAjaxReadyStateChange $ajaxRequest');
    return AjaxRequestAction.PROCEED;
  }
```

### CODE REVIEW

**Comment by pichillilorenzo** [comment]
Thanks, I will update the same code for iOS and macOS.
By the way, the fix should be `&& self.isAsync` and not `&& result.isAsync`, otherwise if you set `isAsync` to `false` on Flutter side, you will have the same exception.

**Comment by pichillilorenzo** [comment]
Unfortunately, due to Flutter platform channels async nature and the async javascript evaluation WebView method, if you use `useShouldInterceptAjaxRequest` and the ajax request uses `isAsync` with `false`, the `XMLHttpRequest.send()` will not wait for the response.
Probably, I should update the docs about it.
The `shouldInterceptAjaxRequest` and the other ajax events are custom, there is no official WebView native API.

**Comment by EArminjon** [comment]
Oh ! thanks for your answer !

**Comment by pichillilorenzo** [comment]
In the meantime, I have released new versions for android, ios and macos platform implementation packages.
You can get the fix on latest plugin version 6 using `flutter upgrade`.

**Pull request merged**
