### PR TITLE
fix flutter 3.22.2 compability

### PR DESCRIPTION
**Pull request by toshiossada**
fix flutter 3.22.2 compability

### CODE REVIEW

**Review by GabriellArthur — APPROVED** [review]

**Comment by shubhamsinghmutualmobile** [comment]
Can this PR be merged now if we're not waiting for anything else?

**Comment by francis94c** [comment]
Merging this PR is like being a super hero right now... 😄

**Review by JoseBarreto1 — APPROVED** [review]

**Review by JoseBarreto1 — CHANGES_REQUESTED** [review]
Publishable packages can't have 'path' dependencies.

**Comment by pichillilorenzo** [comment]
Released new version 6.1.0

**Pull request closed without merging**
