### PR TITLE
fix: xcode 15 related bug

### PR DESCRIPTION
**Pull request by nesquikm**
## Connection with issue(s)

Resolve issue #1787, #1786 and #1783

## Testing and Review Notes

Just try to compile with Xcode 15.

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers

### CODE REVIEW

**Comment by christianwbc** [comment]
Thanks @nesquikm

**Comment by itxtoledo** [comment]
This PR need to be merged as soon as possible @pichillilorenzo

**Comment by erubio-gp** [comment]
I need this fix as well, its blocking our iOS 17 support update. Thank yall for working on this

**Comment by AugustoResende** [comment]
> I need this fix as well, its blocking our iOS 17 support update. Thank yall for working on this

Workaround for local:
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1735#issuecomment-1699023475

Workaround for build pipeline:
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1783#issuecomment-1725173736

**Review by AugustoResende — APPROVED** [review]

**Comment by erubio-gp** [comment]
> > I need this fix as well, its blocking our iOS 17 support update. Thank yall for working on this
> 
> Workaround for local: [#1735 (comment)](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1735#issuecomment-1699023475)
> 
> Workaround for build pipeline: [#1783 (comment)](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1783#issuecomment-1725173736)

I just added the local workaround. Thank you!

**Comment by Binozo** [comment]
Looking forward to getting this fix released as soon as possible 😄

**Comment by marwfair** [comment]
If you need to make a build before the change is published, update your pubspec.yaml to point to the git branch with the change:
```
  flutter_inappwebview:
     git:
      url: https://github.com/nesquikm/flutter_inappwebview
      ref: heads/v5.7.2+3_fix_xcode_17
```

**Comment by Binozo** [comment]
Sadly I can't fix the error on my part :(

```
Running Xcode build...                                                  
Xcode build done.                                           32,1s
Failed to build iOS app
Swift Compiler Error (Xcode): Expected value in expression
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/System/Library/Framework
s/WebKit.framework/Headers/WKWebsiteDataStore.h:112:52


Swift Compiler Error (Xcode): Could not build Objective-C module 'WebKit'


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

```

Can anyone help me?
I already tried all the suggested workarounds

That's what line 112 looks like:
```
#if ((TARGET_OS_OSX && __MAC_OS_X_VERSION_MAX_ALLOWED >= 160000) \
```

**Comment by erubio-gp** [comment]
> Sadly I can't fix the error on my part :(
> 
> 
> 
> ```
> 
> Running Xcode build...                                                  
> 
> Xcode build done.                                           32,1s
> 
> Failed to build iOS app
> 
> Swift Compiler Error (Xcode): Expected value in expression
> 
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/System/Library/Framework
> 
> s/WebKit.framework/Headers/WKWebsiteDataStore.h:112:52
> 
> 
> 
> 
> 
> Swift Compiler Error (Xcode): Could not build Objective-C module 'WebKit'
> 
> 
> 
> 
> 
> Could not build the application for the simulator.
> 
> Error launching application on iPhone 15 Pro Max.
> 
> 
> 
> ```
> 
> 
> 
> Can anyone help me?
> 
> I already tried all the suggested workarounds
> 
> 
> 
> That's what line 112 looks like:
> 
> ```
> 
> #if ((TARGET_OS_OSX && __MAC_OS_X_VERSION_MAX_ALLOWED >= 160000) \
> 
> ```

You'll need to edit the file and change it to "180000"

**Comment by anchao-lu** [comment]
flutter_inappwebview: ^6.0.0-beta.24+1 also needs to be fixed

**Comment by w3ggy** [comment]
Any chance to deploy it soon? 😅

**Comment by oguibueno** [comment]
I'm wondering if @pichillilorenzo is in a sabbatical year. 😂

**Comment by nesquikm** [comment]
> flutter_inappwebview: ^6.0.0-beta.24+1 also needs to be fixed

Sure, there is another PR: https://github.com/pichillilorenzo/flutter_inappwebview/pull/1801

**Comment by paulopicasso** [comment]
Somewhat irrelevant, but I'm pretty sure it's Xcode 15 right?

**Comment by Binozo** [comment]
> Somewhat irrelevant, but I'm pretty sure it's Xcode 15 right?

Yes, I manually downloaded Xcode 14 from `https://developer.apple.com/download/all/` and built my app for iOS 16. Worked all fine

**Comment by GorinMaxim** [comment]
maybe you have some release dates?

**Review by fwilliamconceicao — APPROVED** [review]
This need to be merged asap, it's breaking crisp plugin and others too.

**Comment by pichillilorenzo** [comment]
Released new version `5.8.0` and `6.0.0-beta.25` with that fix! Thanks!

**Comment by StanislavNemytov** [comment]
I have the same issue. What's happened?
Before update Xcode, I've worked on the project. Then I update Xcode to 15v. Then I open a project using recents files (click on Xcode icon and see the list of last projects). Then I realised that it can be something else. I find the project file in the Finder and open it by double click. That's all, it works.

**Pull request merged**
