### PR TITLE
fix. Crash happens when HeadlessInAppWebView's dispose function is called in iOS

### PR DESCRIPTION
**Pull request by hoanglm4**
## Connection with issue(s)

Resolve issue #881, #972

Connected to #???

## To Do

- [ x ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by congthang1** [comment]
thanks this fixed. working

**Comment by vaind** [comment]
I can confirm this fixes the issue for me as well.

**Comment by koteesy** [comment]
Can confirm this fix issue for me, please @pichillilorenzo accept that pull

**Comment by AlexSmirnov9107** [comment]
same for me, please @pichillilorenzo accept that pull

**Comment by dev-ltk** [comment]
Can confirm this works.

**Pull request merged**
