### PR TITLE
Focus request implementation for Android/iOS

### PR DESCRIPTION
**Pull request by yamaha252**
## Connection with issue(s)

Resolve issue #1974

### CODE REVIEW

**Comment by fhdeodato** [comment]
This is cool fix, thanks. Hope to get it in the main project soon.

any updates on this @pichillilorenzo ?

**Comment by fhdeodato** [comment]
Hey @yamaha252 I did some test using your code and the problem is almost solved for android devices

the focus in the field works, but not able to get the keyboard (tried release and debug versions as well)

for iOS is working great, no issue I could detect...

**Comment by h3nr1ke** [comment]
Hey all

just to comment that I found a "not so elegant" workaround to get the focus working for android devices


```dart
Stack(
  children: [
    // ADD A TEXT FIELD WITH TRANSPARENT COLOR FOR THE VISIBLE ITEMS
    // THIS SHOULD BE ADDED ONLY FOR ANDROID APPs IF YOU IMPLEMENTED THE 
    // REQUESTFOCUS FUNCTION AVAILABLE HERE
    // https://github.com/pichillilorenzo/flutter_inappwebview/pull/2168
    Platform.isAndroid ? 
      const TextField(
        autofocus: true,
        decoration: InputDecoration(
          hintText: '',
          hintStyle: TextStyle(color: Colors.transparent),
          focusedBorder: UnderlineInputBorder(
            borderSide: BorderSide(color: Colors.transparent),
          ),
          enabledBorder: UnderlineInputBorder(
            borderSide: BorderSide(color: Colors.transparent),
          ),
        ),
        cursorColor: Colors.transparent,
        style: TextStyle(color: Colors.transparent),
      )
      : const SizedBox.shrink(),
    InAppWebView(
      key: webViewKey,
      initialUrlRequest: URLRequest(
        headers: initialHeaders,
        url: WebUri(widget.loadingUrl),
      ),
      initialSettings: configs.getOptions(),

      onLoadStop: (controller, url) async {
        // this method is still not in the main code
        // please take a look here
        // https://github.com/pichillilorenzo/flutter_inappwebview/pull/2168
        await webViewController.requestFocus();

        // request focus for text element inside the page
        // in this example, search-box-field is the id of a input element
        // It was added a timeout just in case, but you can try with or without 
        // to see what happen in your app
        await webViewController.evaluateJavascript(
          source:'''
            setTimeout(()=>{
              console.log("timeout do search-box-field focus"); 
              document.getElementById("search-box-field").focus();},
              200
            );
          ''',
        );
      },
    ),
  ]
);
```

The main idea is to get the focus in the widget and open the keyboard

Once the keyboard is visible we asked the focus to the webview, and it works 

the tradeoff is the the keyboard opens very fast so it looks like a delay, but it works for Android devices.

Please take in consideration that this is using the new `requestFocus` implementation that is not yet in the main branch

please take a look here

https://github.com/pichillilorenzo/flutter_inappwebview/pull/2168

**Comment by h3nr1ke** [comment]
Just to mention that there is no need to add the  `requestFocus` in the file `flutter_inappwebview/flutter_inappwebview_android/android/src/main/java/com/pichillilorenzo/flutter_inappwebview_android/webview/InAppWebViewInterface.java` since it is asking to override in the implementation of 

`flutter_inappwebview/flutter_inappwebview_android/android/src/main/java/com/pichillilorenzo/flutter_inappwebview_android/webview/in_app_webview/InAppWebView.java`

and the class extends  `InputAwareWebView` that already extends `WebView` 

the request method will be there anyway and since the implementation has no parameters or return value, we just need to call it.

**Comment by h3nr1ke** [comment]
I tried the changes and it helps but didn't solved my issues (withtout the requestFocus implementation was not easy to trigger the focus in the right moment)

but for Android I commented here https://github.com/pichillilorenzo/flutter_inappwebview/issues/1974

For iOS I used the solution presented here https://github.com/Choices-js/Choices/issues/577

with the combination of all, I was able to get the focus working fine from a search input inside a page loaded using in app webview

=)

**Comment by danimnh** [comment]
adding requestFocus by extending the package works. Will be very helpful to have this merged. Thanks!

**Comment by arrrrny** [comment]
@yamaha252 @h3nr1ke @fhdeodato @danimnh @daanporon 

Open your PR on the forked project [here](https://github.com/arrrrny/zikzak_inappwebview) and I will merge. There is a new package now. [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview)

**Pull request merged**
