### PR TITLE
fix: error: stored properties cannot be marked potentially unavailable with '@available'

### PR DESCRIPTION
**Pull request by VictorUvarov**
## Connection with issue(s)

Resolve issue #1312

Connected to #1310, #1216

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by mikhael28** [comment]
@pichillilorenzo would you consider merging this in?

**Review by pavel604 — APPROVED** [review]
Tested, works :)

**Comment by ne3Vubeki** [comment]
We wait

**Comment by sajadmaster** [comment]
When can we expect to see this change? I can't run iOS due to this issue.
Cheers

**Comment by Xanonymous-GitHub** [comment]
Wait for use ... please merge

**Comment by santiago-parodi** [comment]
working!

**Review by abdoosaed — APPROVED** [review]

**Comment by pichillilorenzo** [comment]
Released new version `5.4.3+8` with the fix!

**Pull request closed without merging**
