### PR TITLE
fix: update proguard rules

### PR DESCRIPTION
**Pull request by holzgeist**
## Connection with issue(s)

Resolve issue #2139

## Testing and Review Notes

Steps to reproduce are mentioned in above Issue. This PR solves the error message for me.

The change originates from flutter output in the error message. Applying the same change to the local `proguard-rules.pro` file does not work unfortunately

## Screenshots or Videos

N/A

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by komaxx** [comment]
Looks good to me.

**Comment by Harishwarrior** [comment]
duplicate of #2102

**Comment by holzgeist** [comment]
oh, thanks for pointing it out. I only looked for potential duplicate issues, not for PRs. I'll close this in favor of the older one

**Comment by EchoEllet** [comment]
> Applying the same change to the local proguard-rules.pro file does not work unfortunately

Have you already applied this file in Gradle configuration?

**Pull request closed without merging**
